version: '3.4'
services:
  dockerizedPuppeteerSharp:
    image: ${DOCKER_REGISTRY-}dockerizedPuppeteerSharp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://*:8085
    ports:
      - 8085:80